name: CI
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  build:
    name: Build, lint, and test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      # TODO add cache of deps here

      - name: Install dependencies
        run: npm install

      - name: Check types
        run: npm run tsc

      - name: Unit test
        run: npm test
